export { Collection } from './Collection/Collection';
export { CollectionBlog } from './CollectionBlog/CollectionBlog'
export { Home } from './Home/Home';
export { Login } from './Login/Login';
export { Main } from './Main/Main';
export { Map } from './Map/Map';
export { Profile } from './Profile/Profile';
export { Register } from './Register/Register';
export { Review } from './Review/Review';
export { NewCollection } from './NewCollection/NewCollection';